services:
  web:
    environment:
      - RAILS_ENV=development
      - BUNDLE_WITHOUT=
      - RAILS_SERVE_STATIC_FILES=true
    volumes:
      - .:/rails
    ports:
      - "3000:3000"

  css:
    build: .
    command: bin/rails tailwindcss:watch
    environment:
      - RAILS_ENV=development
      - BUNDLE_WITHOUT=
      - DATABASE_URL=mysql2://root:password@db:3306/nasa_app_development
    volumes:
      - .:/rails
    depends_on:
      - db

  worker:
    environment:
      - RAILS_ENV=development
      - BUNDLE_WITHOUT=
    volumes:
      - .:/rails
